##
## Copyright (c) 2020 Andrew Cottam.
##
## This file is part of marxanweb/general
## (see https://github.com/marxanweb/general).
##
## License: European Union Public Licence V. 1.2, see https://opensource.org/licenses/EUPL-1.2
##
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  toc_levels: 1..3
