import { Map, View } from 'ol';
import OSM from 'ol/source/OSM';
import { Fill, Stroke } from 'ol/style';
import Style from 'ol/style/Style';
import { Overlay } from 'ol';
import { useGeographic, transformExtent } from "ol/proj";
import TileLayer from 'ol/layer/WebGLTile';
import VectorLayer from 'ol/layer/Vector';
import VectorTileLayer from 'ol/layer/VectorTile';
import WebGLPointsLayer from 'ol/layer/WebGLPoints';
import ZoomToExtent from 'ol/control/ZoomToExtent';
import { defaults as defaultControls } from 'ol/control/defaults';
import VectorSource from 'ol/source/Vector';
import VectorTileSource from 'ol/source/VectorTile';
import GeoJSON from 'ol/format/GeoJSON';
import MVT from 'ol/format/MVT';
import TileState from 'ol/TileState';
import { bbox as bboxStrategy } from 'ol/loadingstrategy';
import { apply } from 'ol-mapbox-style';

// FlatGeobuf
import { deserialize as fgbDeserialize } from 'flatgeobuf/lib/mjs/geojson';

// Firebase
import { initializeApp } from "firebase/app";
import { getAuth, GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { getFirestore, getDoc, doc, collection } from "firebase/firestore";

useGeographic();

// Firebase config
const firebaseConfig = {
    apiKey: "AIzaSyAzrhJkckakoJLnRThTDvNRwyE29k7DDGQ",
    authDomain: "restor-poc-apps-b3414.firebaseapp.com",
    projectId: "restor-poc-apps-b3414",
    storageBucket: "restor-poc-apps-b3414.appspot.com",
    messagingSenderId: "1043831538397",
    appId: "1:1043831538397:web:50d6c71e135234ef4b9134"
};

const firebase_app = initializeApp(firebaseConfig);
const auth = getAuth(firebase_app);
const provider = new GoogleAuthProvider();
// Restrict/hint the Google account chooser to the restor.eco Workspace account
provider.setCustomParameters({ hd: 'restor.eco', login_hint: 'andrew@restor.eco' });
const firestore = getFirestore(firebase_app);

// Always call the deployed GCP cloud functions, even when running the frontend
// locally — there's no local emulator for these proxies to fall back to.
const FGB_PROXY_URL = 'https://europe-west6-restor-gis.cloudfunctions.net/fgb_proxy';
const MVT_PROXY_URL = 'https://europe-west6-restor-gis.cloudfunctions.net/mvt_proxy';

// Cutover zoom between the MVT and FlatGeobuf sources (used by both the polygon and
// centroid layer pairs): below/at this level, tiles from the pre-generated MVT pyramid
// (fast, zoom 0-10, generated by cloud_functions/export-sites-to-mvt); above it, live
// FlatGeobuf features.
const SOURCE_CUTOVER_ZOOM = 10;

// Helper function to parse URL parameters
function getUrlParameters() {
    const urlParams = new URLSearchParams(window.location.search);
    const lat = urlParams.get('lat');
    const lng = urlParams.get('lng') || urlParams.get('lon');
    const zoom = urlParams.get('zoom');

    const result = {};

    if (lat && !isNaN(parseFloat(lat))) {
        result.lat = parseFloat(lat);
    }

    if (lng && !isNaN(parseFloat(lng))) {
        result.lng = parseFloat(lng);
    }

    if (zoom && !isNaN(parseFloat(zoom))) {
        result.zoom = parseFloat(zoom);
    }

    return result;
}

// variables
var visibleStatuses = new Set(['PUBLIC']);
var logged_in = false;
var current_user = null;

const geoJsonFormat = new GeoJSON();

// Sites vector source, loaded directly from the FlatGeobuf file via fgb_proxy
// (requires a logged-in, whitelisted user, same as dist-alert's FGB mode)
const vector_tile_source = new VectorSource({ strategy: bboxStrategy });
vector_tile_source.setLoader(async function (extent, _resolution, projection, success, failure) {
    if (!current_user) {
        vector_tile_source.removeLoadedExtent(extent);
        return;
    }
    try {
        const [minX, minY, maxX, maxY] = transformExtent(extent, projection, 'EPSG:4326');
        const rect = { minX, minY, maxX, maxY };
        const idToken = await current_user.getIdToken();
        const headers = { 'Authorization': `Bearer ${idToken}` };

        const features = [];
        for await (const geoJsonFeature of fgbDeserialize(`${FGB_PROXY_URL}?source=sites_plus_checks`, rect, undefined, false, headers)) {
            const olFeature = geoJsonFormat.readFeature(geoJsonFeature, {
                featureProjection: projection,
                dataProjection: 'EPSG:4326',
            });
            features.push(olFeature);
        }
        vector_tile_source.addFeatures(features);
        success?.(features);
    } catch (e) {
        console.error('FGB load error:', e);
        failure?.();
        vector_tile_source.removeLoadedExtent(extent);
    }
});

// Site centroid vector source: loaded once, in full, from sites_centroids.fgb (a
// deliberately narrow schema — see cloud_functions/export-sites-to-fgb — small enough
// to load entirely up front) rather than per-viewport like the polygon sources. A
// WebGLPointsLayer wants its whole dataset in one GPU buffer and shows it at every
// zoom, so there's no viewport-scoped bbox to load against here.
const centroid_source = new VectorSource();

// Fetched in bounded chunks (rather than one request for the whole file, or via
// FlatGeobuf's spatial-index reader with a world-covering bbox) since either of those
// collapses into one or a few enormous byte-range requests — fgb_proxy just does
// blob.download_as_bytes(start, end) and returns that whole span as a single
// response, which trips "Response size was too large" and fails to deliver data.
// Chunking keeps every individual response small regardless of the file's total size.
const FGB_CHUNK_SIZE = 8 * 1024 * 1024; // 8MB
const CONTENT_RANGE_TOTAL_RE = /bytes \d+-\d+\/(\d+)/;

async function fetchEntireFile(url, headers, onProgress) {
    const chunks = [];
    let start = 0;
    let total = Infinity;
    while (start < total) {
        const end = start + FGB_CHUNK_SIZE - 1;
        const response = await fetch(url, { headers: { ...headers, Range: `bytes=${start}-${end}` } });
        if (!response.ok) throw new Error(`FGB chunk fetch failed: ${response.status}`);
        const contentRange = response.headers.get('Content-Range');
        const match = contentRange && contentRange.match(CONTENT_RANGE_TOTAL_RE);
        if (match) total = parseInt(match[1], 10);
        const chunk = new Uint8Array(await response.arrayBuffer());
        chunks.push(chunk);
        if (!match) break; // server didn't honor the Range request; treat this as the whole file
        start = end + 1;
        onProgress?.(Math.min(start, total), total);
    }
    const buffer = new Uint8Array(chunks.reduce((sum, c) => sum + c.length, 0));
    let offset = 0;
    for (const chunk of chunks) {
        buffer.set(chunk, offset);
        offset += chunk.length;
    }
    return buffer;
}

function setCentroidLoadingIndicator(visible, percent) {
    const el = document.getElementById('centroid-loading');
    if (!el) return;
    el.hidden = !visible;
    if (visible && percent !== undefined) {
        document.getElementById('centroid-loading-pct').textContent = `${percent}%`;
    }
}

// Disabled by default in index.html and whenever centroid_source is cleared (logout,
// or a fresh load in progress) — there's nothing to show in "centroids" mode until
// loadAllCentroids has actually populated the source, so switching to it early would
// just render an empty layer with no indication why.
function setCentroidsModeEnabled(enabled) {
    const radio = document.getElementById('mode-centroids');
    if (radio) radio.disabled = !enabled;
}

async function loadAllCentroids() {
    if (!current_user) return;
    setCentroidsModeEnabled(false);
    setCentroidLoadingIndicator(true, 0);
    try {
        const idToken = await current_user.getIdToken();
        const headers = { 'Authorization': `Bearer ${idToken}` };
        const buffer = await fetchEntireFile(`${FGB_PROXY_URL}?source=sites_centroids`, headers, (loaded, total) => {
            setCentroidLoadingIndicator(true, Math.round((loaded / total) * 100));
        });

        // A plain Uint8Array (rather than a bbox rect) makes fgbDeserialize read the
        // file sequentially front-to-back with no spatial-index/range-request involved.
        const features = [];
        for await (const geoJsonFeature of fgbDeserialize(buffer)) {
            const olFeature = geoJsonFormat.readFeature(geoJsonFeature, {
                featureProjection: 'EPSG:4326',
                dataProjection: 'EPSG:4326',
            });
            // Initialized on every feature up front (rather than left undefined until
            // first hovered) so the WebGL style's ['get', 'hovered'] attribute has a
            // consistent numeric type to compile against from the start.
            olFeature.set('hovered', 0);
            features.push(olFeature);
        }
        centroid_source.clear();
        centroid_source.addFeatures(features);
        setCentroidsModeEnabled(true);
    } catch (e) {
        console.error('FGB centroids load error:', e);
    } finally {
        setCentroidLoadingIndicator(false);
    }
}

// Public/private sites are rendered differently (solid green vs dashed amber),
// matching the legend swatches next to the visibility switches.
const public_style = new Style({ fill: new Fill({ color: 'rgba(99, 148, 69, 0.2)', }), stroke: new Stroke({ color: 'rgba(99, 148, 69, 0.8)', width: 1.5 }) });
const private_style = new Style({ fill: new Fill({ color: 'rgba(179, 140, 80, 0.18)', }), stroke: new Stroke({ color: 'rgba(179, 140, 80, 0.9)', width: 1.5, lineDash: [4, 4] }) });
// Hover highlight keeps each visibility's own color/dash, just heavier, rather than a single shared color.
const public_highlight_style = new Style({ fill: new Fill({ color: 'rgba(99, 148, 69, 0.3)', }), stroke: new Stroke({ color: 'rgba(99, 148, 69, 0.7)', width: 2 }) });
const private_highlight_style = new Style({ fill: new Fill({ color: 'rgba(179, 140, 80, 0.28)', }), stroke: new Stroke({ color: 'rgba(179, 140, 80, 0.8)', width: 2, lineDash: [4, 4] }) });

// Integer-code -> label mappings for the enum columns that sites_centroids.fgb and
// sites_plus_checks.fgb now store as small ints instead of repeating full text per
// row (see cloud_functions/export-sites-to-fgb/main.py's matching *_CODES dicts,
// which these must stay in sync with). The MVT tile pyramid (export-sites-to-mvt,
// not yet migrated) still stores these columns as plain text — decodeEnum() below
// passes text values through unchanged, so both schemas work through the same code.
const SITE_TYPE_LABELS = {
    0: 'RESTORATION',
    1: 'CONSERVATION',
    2: 'LANDSCAPE',
    3: 'AREA_OF_INTEREST',
    4: 'SUSTAINABLE_LAND_MANAGEMENT',
};
const STAGE_LABELS = {
    0: 'PLANNING',
    1: 'ONGOING',
    2: 'COMPLETED',
};
const PRE_INTERVENTION_LAND_USE_LABELS = {
    0: 'DEFORESTED_LAND',
    1: 'GRAZING_LAND',
    2: 'DEGRADED_FOREST',
    3: 'URBAN',
    4: 'NOT_USED_FOR_PRODUCTION',
    5: 'MINING_OR_EXTRACTIVES',
    6: 'NOT_APPLICABLE',
    7: 'DEGRADED_AQUATIC_HABITATS',
    8: 'INDUSTRIAL',
    9: 'CROPLAND',
    10: 'OTHER',
};
const INTERVENTION_TYPE_LABELS = {
    0: 'ACTIVE_RESTORATION',
    1: 'AGROFORESTRY',
    2: 'ASSISTED_NATURAL_REGENERATION',
    3: 'CONSERVATION_AND_ECOSYSTEM_PROTECTION',
    4: 'HUMAN_DISTURBANCE_REMOVAL',
    5: 'PASSIVE_NATURAL_REGENERATION',
    6: 'RESTORING_NATURAL_DISTURBANCE_REGIMES',
    7: 'SUSTAINABLE_AGRICULTURE',
    8: 'SUSTAINABLE_FORESTRY',
    9: 'OTHER_SUSTAINABLE_PRODUCTION',
    10: 'OTHER',
    // -1 (unmapped/legacy, e.g. a stray LANDSCAPE_SCALE_INTERVENTION row) intentionally
    // has no entry, so decodeEnum() returns undefined for it, same as a missing value.
};
const POST_INTERVENTION_LAND_COVER_LABELS = {
    0: 'ARID',
    1: 'COASTAL',
    2: 'CROPLAND',
    3: 'GRASSLAND',
    4: 'GRAZING_LAND',
    5: 'LAKE',
    6: 'MANGROVE',
    7: 'MARINE',
    8: 'NATURAL_FOREST',
    9: 'PEATLAND',
    10: 'PRODUCTION_FOREST',
    11: 'RIPARIAN',
    12: 'RIVER',
    13: 'SAVANNAH',
    14: 'SEMI_ARID',
    15: 'SHRUBLAND',
    16: 'TUNDRA',
    17: 'WETLAND',
    18: 'MULTIPLE_HABITATS',
    19: 'OTHER',
};
const SITE_VISIBILITY_LABELS = {
    0: 'PUBLIC',
    1: 'PRIVATE',
};

// Decodes a possibly int-coded enum property back to its text label. `value` is
// passed through unchanged if it's not a number, so features from the (not yet
// migrated) MVT tile sources, which still store plain text, work the same way.
function decodeEnum(value, labels) {
    if (typeof value !== 'number') return value;
    return labels[value];
}

// Returns a site's area in km², regardless of which schema its feature came from:
// the MVT tile sources still carry full-precision surface_area_km2; the newer FGB
// centroids/plus-checks exports carry a pre-rounded surface_area_ha instead (with a
// sentinel 0 meaning "<1 ha" — safely treated as its true minimum here, since that
// only ever makes a site look smaller than it is, never hides one that should show).
function getSurfaceAreaKm2(feature) {
    const km2 = feature.get('surface_area_km2');
    if (km2 !== undefined) return km2;
    const ha = feature.get('surface_area_ha');
    return ha !== undefined ? ha / 100 : undefined;
}

// Same area lookup as getSurfaceAreaKm2, but formatted for display and operating on
// a plain properties object (as buildPopupHtml receives) rather than a feature.
function formatSurfaceAreaHa(props) {
    const ha = props['surface_area_ha'];
    if (ha !== undefined) {
        return ha === 0 ? '<1 ha' : `${formatNumber(ha)} ha`;
    }
    const km2 = props['surface_area_km2'];
    if (km2 === undefined) return '';
    const haFromKm2 = km2 * 100;
    if (haFromKm2 < 1) return '<1 ha';
    const formatted = formatNumber(haFromKm2);
    return formatted ? `${formatted} ha` : '';
}

// The area slider's native <input type="range"> value is a *position* (0..
// AREA_SLIDER_STEPS), not the km² threshold itself — mapped through an exponential
// curve so it stays linear in decades rather than in km². Real sites span from ~1 ha
// up to thousands of km², so a slider linear in km² leaves everything below ~1000 km²
// crammed into the first couple of pixels: values like 1/10/100/1000 ha were all the
// same leftmost slider pixel. Mapping position -> 10^(log(min) + t*(log(max)-log(min)))
// instead gives each order of magnitude equal space on the track.
const AREA_SLIDER_MIN_KM2 = 0.01; // 1 ha — the practical floor; below this nothing new becomes selectable anyway
const AREA_SLIDER_MAX_KM2 = 1000000; // unchanged from the slider's previous linear max
const AREA_SLIDER_STEPS = 1000;
const AREA_SLIDER_LOG_MIN = Math.log10(AREA_SLIDER_MIN_KM2);
const AREA_SLIDER_LOG_MAX = Math.log10(AREA_SLIDER_MAX_KM2);

function sliderPositionToAreaKm2(position) {
    const t = position / AREA_SLIDER_STEPS;
    return Math.pow(10, AREA_SLIDER_LOG_MIN + t * (AREA_SLIDER_LOG_MAX - AREA_SLIDER_LOG_MIN));
}

function areaKm2ToSliderPosition(areaKm2) {
    const clamped = Math.min(Math.max(areaKm2, AREA_SLIDER_MIN_KM2), AREA_SLIDER_MAX_KM2);
    const t = (Math.log10(clamped) - AREA_SLIDER_LOG_MIN) / (AREA_SLIDER_LOG_MAX - AREA_SLIDER_LOG_MIN);
    return Math.round(t * AREA_SLIDER_STEPS);
}

function getAreaThresholdKm2() {
    return sliderPositionToAreaKm2(parseFloat(document.getElementById('slider').value));
}

// Toggled by the "Mangrove proximity" switch — when on, only sites whose
// verification_checks includes a "Proximity to mangroves" check with status "Valid"
// are shown. Only sites_plus_checks.fgb/the MVT pyramid carry verification_checks
// (see parseListField's comment on that column) — sites_centroids.fgb's narrow schema
// doesn't, so this filter has no effect in Centroids mode; the toggle is disabled
// there (see updateMangroveFilterAvailability) rather than silently doing nothing.
var mangroveProximityOnly = false;
const MANGROVE_PROXIMITY_CHECK_NAME = 'Proximity to mangroves';

function hasValidMangroveProximityCheck(feature) {
    const checks = parseListField(feature.get('verification_checks')).filter(Boolean);
    return checks.some((check) =>
        check && typeof check === 'object' &&
        check.name === MANGROVE_PROXIMITY_CHECK_NAME &&
        check.status === 'Valid'
    );
}

// Shared visibility predicate for the sites layers, so both respect the same
// area threshold/status filters without duplicating logic.
function isSiteVisible(feature) {
    const threshold = getAreaThresholdKm2();
    const areaKm2 = getSurfaceAreaKm2(feature);
    const vis = decodeEnum(feature.get('site_visibility'), SITE_VISIBILITY_LABELS);
    // A negative area is bad/invalid data (e.g. a malformed polygon), never a real
    // site size — always hide it rather than let it slip through as "smaller than
    // any threshold".
    return !(
        areaKm2 > threshold || areaKm2 < 0 || !visibleStatuses.has(vis) ||
        (mangroveProximityOnly && !hasValidMangroveProximityCheck(feature))
    );
}

// Centroid layer style: a literal WebGL expression style, not an ol/style/Style
// function — variables are pushed via centroid_webgl_layer.updateStyleVariables()
// whenever the area slider/status checkboxes change, since WebGL styles can't run
// arbitrary JS per feature the way siteStyle() does for the polygon layers.
// site_visibility's 0/1 codes are hardcoded here (rather than going through
// decodeEnum/SITE_VISIBILITY_LABELS) since expressions can't call into JS — keep this
// in sync with SITE_VISIBILITY_LABELS and export-sites-to-fgb's SITE_VISIBILITY_CODES.
//
// Hover highlighting is driven by a per-feature `hovered` attribute (0/1, set directly
// on the hit ol/Feature via setHoveredCentroidFeature) rather than a style variable
// compared against feature id: the WebGL/GPU expression compiler has no "to-string"
// operator (unlike the general expression language), so there's no safe way to compare
// an id of unknown numeric-vs-string type against a variable at the GPU level.
//
// Radius kept small since at low zoom hundreds of thousands of these overlap on
// screen — smaller circles mean less overdraw/alpha-blending work per repaint.
//
// Neither circle-radius NOR circle-stroke-width depend on `hovered` (an earlier
// version changed one, then the other, and both caused the same problem):
// WebGLPointsLayer's hit-test picking pass samples the same rendered footprint as the
// visual style, including the stroke, not just the fill radius — so making the circle
// *or its outline* bigger on hover changes the hit-test footprint for the very next
// pointermove. Near densely overlapping points that created a feedback loop (hover
// enlarges the marker -> picking geometry shifts -> a different/no feature hit ->
// un-hover shrinks it back -> re-hit -> grows again), which looked like the marker
// rapidly growing/shrinking and the popup flickering in lockstep. Keeping the entire
// footprint (radius + stroke width) constant and indicating hover with color alone
// (which doesn't feed the picking geometry) avoids that loop entirely.
const centroid_webgl_style = {
    variables: {
        // thresholdHa mirrors the slider's km² threshold converted to hectares, since
        // sites_centroids.fgb stores surface_area_ha, not surface_area_km2.
        thresholdHa: getAreaThresholdKm2() * 100,
        showPublic: visibleStatuses.has('PUBLIC') ? 1 : 0,
        showPrivate: visibleStatuses.has('PRIVATE') ? 1 : 0,
    },
    filter: ['all',
        ['<=', ['get', 'surface_area_ha'], ['var', 'thresholdHa']],
        ['any',
            ['all', ['==', ['get', 'site_visibility'], 0], ['==', ['var', 'showPublic'], 1]],
            ['all', ['==', ['get', 'site_visibility'], 1], ['==', ['var', 'showPrivate'], 1]],
        ],
    ],
    'circle-radius': 2,
    'circle-fill-color': ['case',
        ['==', ['get', 'hovered'], 1],
        ['case', ['==', ['get', 'site_visibility'], 1], 'rgba(179, 140, 80, 1)', 'rgba(99, 148, 69, 1)'],
        ['==', ['get', 'site_visibility'], 1], 'rgba(179, 140, 80, 0.9)',
        'rgba(99, 148, 69, 0.9)',
    ],
    'circle-stroke-color': ['case', ['==', ['get', 'hovered'], 1], '#222222', 'white'],
    'circle-stroke-width': 0.5,
};

// The single "confirmed" hover target driving both the popup (content/visibility)
// and the centroid marker highlight. Both used to react directly to each pointermove
// event's raw hit-test result, but near densely packed/overlapping points, which
// feature "wins" the hit-test can flip between consecutive events even when the
// cursor hasn't meaningfully moved — that showed up as both the popup content and the
// marker highlight flickering in lockstep with that noise.
//
// Acquiring a new hover (including switching directly between two different features)
// commits quickly, for a responsive feel. Clearing to "nothing hovered" uses a much
// longer timer instead: brief gaps in the raw hit-test between competing overlapping
// points (typically lasting only a couple of frames) never actually reach "nothing
// hovered" within that window, so the popup stays visibly stable instead of blinking
// off every time the picking result briefly wavers. It only really disappears once the
// cursor has genuinely been off every site for HOVER_CLEAR_DEBOUNCE_MS.
let hoveredFeature = null;
let hoveredIsCentroid = false;
let pendingHoverFeature; // undefined = no pending change (distinct from null = "nothing hit")
let pendingHoverLayer = null;
let hoverDebounceTimeout = null;
const HOVER_SET_DEBOUNCE_MS = 50;
const HOVER_CLEAR_DEBOUNCE_MS = 1200;

function applyConfirmedHover(feature, layer) {
    if (hoveredFeature === feature) return;
    if (hoveredFeature && hoveredIsCentroid) hoveredFeature.set('hovered', 0);
    hoveredFeature = feature || null;
    hoveredIsCentroid = hoveredFeature !== null && layer === centroid_webgl_layer;
    if (hoveredIsCentroid) hoveredFeature.set('hovered', 1);

    selected_feature.current = hoveredFeature ? hoveredFeature.get('id') : undefined;
    mvt_tile_layer.changed();
    vector_tile_layer.changed();

    // While the click context menu is open, leave the popup showing the clicked
    // feature's info alone — it should stay visible until an action is taken, not
    // disappear just because the cursor moved off that feature (e.g. towards the menu).
    if (feature_menu_feature) return;

    var pu = document.getElementById('popup');
    if (hoveredFeature && hoveredFeature.get('id') !== undefined) {
        pu.style.display = "block";
        pu.innerHTML = buildPopupHtml(hoveredFeature.getProperties());
    } else {
        pu.style.display = "none";
    }
}

function updateHoverCandidate(feature, layer) {
    if (feature === hoveredFeature) {
        // Already confirmed; cancel any pending switch away from it.
        if (hoverDebounceTimeout && pendingHoverFeature !== hoveredFeature) {
            clearTimeout(hoverDebounceTimeout);
            hoverDebounceTimeout = null;
            pendingHoverFeature = undefined;
        }
        return;
    }
    if (pendingHoverFeature === feature) return; // already debouncing towards this
    if (hoverDebounceTimeout) clearTimeout(hoverDebounceTimeout);
    pendingHoverFeature = feature;
    pendingHoverLayer = layer;
    // Only clearing (feature === null) away from a *centroid* gets the long grace
    // period — that's the noisy WebGL hit-test case. Clearing away from a polygon
    // (Canvas-based, deterministic hit-test) doesn't need protection and should hide
    // the popup right away, or it just looks like it's stuck open.
    const delay = feature ? HOVER_SET_DEBOUNCE_MS : (hoveredIsCentroid ? HOVER_CLEAR_DEBOUNCE_MS : 0);
    hoverDebounceTimeout = setTimeout(() => {
        applyConfirmedHover(pendingHoverFeature, pendingHoverLayer);
        hoverDebounceTimeout = null;
        pendingHoverFeature = undefined;
    }, delay);
}

// Render-mode switcher: "geometries" (default) shows sites as their actual polygons
// (mvt_tile_layer/vector_tile_layer); "centroids" shows them as point markers from the
// dedicated sites_centroids.fgb source (centroid_webgl_layer) instead. Structured so a
// future mode (e.g. "heatmap") is just one more branch here.
const RENDER_MODES = ['geometries', 'centroids'];
let renderMode = 'geometries';

function updateLayerVisibilityForRenderMode() {
    const showGeometries = logged_in && renderMode === 'geometries';
    const showCentroids = logged_in && renderMode === 'centroids';
    mvt_tile_layer.setVisible(showGeometries);
    vector_tile_layer.setVisible(showGeometries);
    centroid_webgl_layer.setVisible(showCentroids);
}

function handleRenderModeChange(event) {
    if (!RENDER_MODES.includes(event.target.value)) return;
    renderMode = event.target.value;
    updateLayerVisibilityForRenderMode();
    updateMangroveFilterAvailability();
}

// The mangrove-proximity filter only has data to work with in Geometries mode (see
// isSiteVisible) — disable rather than hide it in Centroids mode, matching the
// "Show site checks" context-menu item's treatment of the same schema gap.
function updateMangroveFilterAvailability() {
    document.getElementById('mangrove-proximity-toggle').disabled = renderMode !== 'geometries';
}

// Shared style logic for the polygon sites layers (MVT or live FGB).
// Styling the hovered feature in place (rather than via a separate highlight layer) means
// hover highlighting works for both sources without needing a source-specific selection layer.
function siteStyle(feature) {
    if (!isSiteVisible(feature)) return null;
    const vis = decodeEnum(feature.get('site_visibility'), SITE_VISIBILITY_LABELS);
    const isSelected = feature.get('id') === selected_feature.current;
    if (isSelected) {
        return vis === 'PRIVATE' ? private_highlight_style : public_highlight_style;
    }
    return vis === 'PRIVATE' ? private_style : public_style;
}

// Authenticated MVT tile-load function, shared by every VectorTileSource reading
// pre-generated tiles from mvt_proxy (requires a logged-in, whitelisted user).
function authenticatedMvtTileLoadFunction(tile, url) {
    if (!current_user) {
        tile.setState(TileState.ERROR);
        return;
    }
    current_user.getIdToken()
        .then((idToken) => fetch(url, { headers: { 'Authorization': `Bearer ${idToken}` } }))
        .then((response) => {
            if (response.status === 204) {
                tile.setFeatures([]);
                tile.setState(TileState.LOADED);
                return;
            }
            if (!response.ok) throw new Error(`MVT tile load failed: ${response.status}`);
            return response.arrayBuffer().then((buffer) => {
                const format = tile.getFormat();
                tile.setFeatures(format.readFeatures(buffer, {
                    extent: tile.extent,
                    featureProjection: tile.projection,
                }));
                tile.setState(TileState.LOADED);
            });
        })
        .catch((e) => {
            console.error('MVT tile load error:', e);
            tile.setState(TileState.ERROR);
        });
}

// Sites vector tile source, reading the pre-generated MVT pyramid via mvt_proxy.
const mvt_tile_source = new VectorTileSource({
    format: new MVT(),
    url: `${MVT_PROXY_URL}/tiles/{z}/{x}/{y}.pbf`,
});
mvt_tile_source.setTileLoadFunction(authenticatedMvtTileLoadFunction);

// Create the sites vector tile layer (zoom 0-10, pre-generated MVT tiles)
const mvt_tile_layer = new VectorTileLayer({
    source: mvt_tile_source,
    maxZoom: SOURCE_CUTOVER_ZOOM,
    visible: false,
    style: siteStyle,
});

// Create the sites vector layer (zoom >8, live FlatGeobuf features)
const vector_tile_layer = new VectorLayer({
    source: vector_tile_source,
    minZoom: SOURCE_CUTOVER_ZOOM,
    visible: false,
    style: siteStyle,
});

// Centroid layer: a single WebGLPointsLayer covering the whole dataset at every zoom
// (no MVT/FGB zoom split — see loadAllCentroids), since sites_centroids.fgb is small
// enough to load in full and WebGL rendering comfortably handles the ~300k+ points
// without the per-feature JS style-callback + Canvas overdraw cost a regular
// VectorLayer/VectorTileLayer would pay at low zoom.
const centroid_webgl_layer = new WebGLPointsLayer({
    source: centroid_source,
    visible: false,
    style: centroid_webgl_style,
});

// Create the map
const urlParams = getUrlParameters();
let initialCenter = [0, 0];
let initialZoom = 0;

if (urlParams.lat !== undefined && urlParams.lng !== undefined) {
    initialCenter = [urlParams.lng, urlParams.lat];
}

if (urlParams.zoom !== undefined) {
    initialZoom = urlParams.zoom;
}

const map = new Map({
    target: 'map',
    // layers: [new TileLayer({ source: new OSM() }), vector_tile_layer],
    view: new View({ center: initialCenter, zoom: initialZoom }),
    // Positioned above the default zoom in/out buttons via the .ol-zoom-extent /
    // .ol-zoom CSS overrides below.
    controls: defaultControls().extend([
        new ZoomToExtent({ extent: [-180, -90, 180, 90], label: '⤢', tipLabel: 'Zoom to full extent' }),
    ]),
});

// Set when a popstate (browser back/forward) handler is applying a URL's lat/lng/zoom
// to the view — the resulting moveend must not itself push a new history entry, or
// every back/forward navigation would immediately re-push a duplicate ahead of it.
let suppressNextHistoryPush = false;
let moveendHistoryTimeout = null;

map.on('moveend', () => {
    const view = map.getView();
    const center = view.getCenter();
    const zoom = view.getZoom();
    const params = new URLSearchParams(window.location.search);
    params.set('lng', center[0].toFixed(6));
    params.set('lat', center[1].toFixed(6));
    params.set('zoom', zoom.toFixed(2));
    const url = `?${params.toString()}`;

    // Debounced so a flurry of moveend events (e.g. scroll-zooming, or a drag
    // immediately followed by small adjustments) collapses into one history entry,
    // rather than flooding back/forward with every intermediate step.
    if (moveendHistoryTimeout) clearTimeout(moveendHistoryTimeout);
    moveendHistoryTimeout = setTimeout(() => {
        moveendHistoryTimeout = null;
        if (suppressNextHistoryPush) {
            suppressNextHistoryPush = false;
            return;
        }
        window.history.pushState(null, '', url);
    }, 500);
});

// Restore the view when the user navigates back/forward through the pan/zoom history
// pushState above builds up.
window.addEventListener('popstate', () => {
    const poppedParams = getUrlParameters();
    if (poppedParams.lat === undefined || poppedParams.lng === undefined) return;
    suppressNextHistoryPush = true;
    map.getView().animate({
        center: [poppedParams.lng, poppedParams.lat],
        zoom: poppedParams.zoom !== undefined ? poppedParams.zoom : map.getView().getZoom(),
        duration: 300,
    });
});

// Apply the MapTiler style
// const styleJson = `https://api.maptiler.com/maps/backdrop/style.json?key=67VOA297U9cciigsJVvm`;
// const styleJson = 'https://api.maptiler.com/maps/dataviz/style.json?key=67VOA297U9cciigsJVvm'; // dataviz with green forests
const styleJson = 'https://api.maptiler.com/maps/a1d2f17b-d57a-45ba-b7c6-4af845f758fb/style.json?key=67VOA297U9cciigsJVvm'; // forests 0% opacity
apply(map, styleJson).then(() => {
    map.addLayer(mvt_tile_layer);
    map.addLayer(vector_tile_layer);
    map.addLayer(centroid_webgl_layer);
});

// Create a selected feature
var selected_feature = {};
// Create a popup
var map_popup = new Overlay({
    element: document.getElementById('popup'),
    offset: [16, 24],
    positioning: 'top-left',
});
map.addOverlay(map_popup);

// Context menu shown on click (rather than immediately opening the checks modal),
// offering "Zoom to site" and "Show site checks" for whichever feature was clicked —
// works the same for polygon (mvt/vector_tile_layer) and centroid (centroid_webgl_layer)
// features.
var feature_menu_feature = null;
var feature_menu_layer = null;
var feature_menu_popup = new Overlay({
    element: document.getElementById('feature-menu'),
    offset: [8, 8],
    positioning: 'top-left',
    // Custom class (in addition to OL's default overlay-container classes) so this
    // overlay's own CSS z-index rule can lift it above the hover popup's overlay
    // container, which otherwise sits on top since it was added to the map first.
    className: 'ol-overlay-container ol-selectable feature-menu-overlay',
});
map.addOverlay(feature_menu_popup);

function showFeatureMenu(feature, layer, coordinate) {
    feature_menu_feature = feature;
    feature_menu_layer = layer;
    feature_menu_popup.setPosition(coordinate);
    document.getElementById('feature-menu').hidden = false;

    // Centroid features come from sites_centroids.fgb's deliberately narrow schema
    // (see loadAllCentroids), which doesn't carry check data — only the polygon
    // sources (mvt_tile_layer/vector_tile_layer) do. Disable rather than hide so the
    // menu's layout/item order stays consistent regardless of render mode.
    const checksButton = document.getElementById('feature-menu-checks');
    checksButton.disabled = layer === centroid_webgl_layer;
    checksButton.title = checksButton.disabled ? 'Only available in Geometries mode' : '';

    // Guarantee the info popup shows this feature (rather than relying on whatever
    // hover state happened to be active already) — it then stays put until an action
    // is taken, per applyConfirmedHover's feature_menu_feature check above.
    const props = feature.getProperties();
    if (props['id'] !== undefined) {
        map_popup.setPosition(coordinate);
        const pu = document.getElementById('popup');
        pu.style.display = "block";
        pu.innerHTML = buildPopupHtml(props);
    }
}

function hideFeatureMenu() {
    document.getElementById('feature-menu').hidden = true;
    feature_menu_feature = null;
    feature_menu_layer = null;
}

function escapeHtml(str) {
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

function safe(value) {
    // geopandas/pandas represents missing values as float NaN, not undefined
    if (value === undefined || value === null) return '';
    if (typeof value === 'number' && isNaN(value)) return '';
    return value;
}

function formatEnum(str) {
    if (!str) return '';
    return str.toLowerCase().split('_').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
}

function formatNumber(value) {
    const num = parseFloat(value);
    if (isNaN(num)) return '';
    return num.toLocaleString(undefined, { maximumFractionDigits: 1 });
}

function parseListField(value) {
    // Some list-valued columns (e.g. photo_ids) are stored as Python-repr strings
    // with single quotes, e.g. "['abc123']".
    // Others (verification_checks) are proper JSON, whose string values may contain
    // apostrophes (e.g. "Pete's patch") — try real JSON first so those aren't corrupted
    // by a blind single-quote-to-double-quote replacement.
    value = safe(value);
    if (value === '') return [];
    if (Array.isArray(value)) return value;
    const trimmed = String(value).trim();
    if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
        try {
            const parsed = JSON.parse(trimmed);
            if (Array.isArray(parsed)) return parsed;
        } catch (e) {
            try {
                const parsed = JSON.parse(trimmed.replace(/'/g, '"'));
                if (Array.isArray(parsed)) return parsed;
            } catch (e2) {
                // fall through and treat as a plain string
            }
        }
    }
    return [trimmed];
}

// Same status colors as openlayers/verify (CheckDiv/ClassificationCheck: green/orange/red, white text)
const CHECK_STATUS_ORDER = ['Invalid', 'Needs Review', 'Valid'];
const CHECK_STATUS_COLORS = { 'Invalid': '#c0605c', 'Needs Review': '#d39a4e', 'Valid': '#6b9b5e' };

function buildVerificationPillsHtml(checks) {
    if (!checks.length) return '';
    const counts = {};
    checks.forEach((check) => {
        const status = (check && typeof check === 'object' ? check.status : check) || 'Unknown';
        counts[status] = (counts[status] || 0) + 1;
    });
    const orderedStatuses = [...CHECK_STATUS_ORDER, ...Object.keys(counts).filter((s) => !CHECK_STATUS_ORDER.includes(s))];
    return orderedStatuses
        .filter((status) => counts[status])
        .map((status) => {
            const color = CHECK_STATUS_COLORS[status] || 'gray';
            return `<span class="popup-check-pill" style="background:${color}" title="${escapeHtml(status)}">${counts[status]}</span>`;
        })
        .join('');
}

function buildChecksModalBody(checks) {
    if (!checks.length) {
        return '<div class="checks-modal-empty">No verification checks available for this site.</div>';
    }
    const sorted = [...checks].sort((a, b) => {
        const statusA = (a && typeof a === 'object' ? a.status : a) || 'Unknown';
        const statusB = (b && typeof b === 'object' ? b.status : b) || 'Unknown';
        const rankA = CHECK_STATUS_ORDER.indexOf(statusA);
        const rankB = CHECK_STATUS_ORDER.indexOf(statusB);
        return (rankA === -1 ? CHECK_STATUS_ORDER.length : rankA) - (rankB === -1 ? CHECK_STATUS_ORDER.length : rankB);
    });
    return sorted.map((check) => {
        const isObject = check && typeof check === 'object';
        const name = isObject ? (check.name || 'Check') : String(check);
        const status = (isObject ? check.status : check) || 'Unknown';
        const message = isObject ? safe(check.status_message) : '';
        const color = CHECK_STATUS_COLORS[status] || 'gray';
        return `
            <div class="check-row">
                <div class="check-info">
                    <div class="check-name">${escapeHtml(name)}</div>
                    ${message ? `<div class="check-message">${escapeHtml(message)}</div>` : ''}
                </div>
                <span class="check-status-pill" style="background:${color}">${escapeHtml(status)}</span>
            </div>
        `;
    }).join('');
}

function openChecksModal(props) {
    const checks = parseListField(props['verification_checks']).filter(Boolean);
    document.getElementById('checks-modal-title').textContent = props['name'] || 'Untitled site';
    document.getElementById('checks-modal-body').innerHTML = buildChecksModalBody(checks);
    document.getElementById('checks-modal-backdrop').classList.add('open');
}

function closeChecksModal() {
    document.getElementById('checks-modal-backdrop').classList.remove('open');
}

function buildPhotoUrl(siteId, photoId) {
    // Same endpoint restor.eco's own frontend uses; redirects (307) to a public GCS object.
    return `https://restor2-prod-1-api.restor.eco/sites/5/${siteId}/photo/${photoId}`;
}

function countryCodeToFlagEmoji(code) {
    if (!code || code.length !== 2 || !/^[a-zA-Z]{2}$/.test(code)) return '';
    const codePoints = code.toUpperCase().split('').map(c => 127397 + c.charCodeAt(0));
    return String.fromCodePoint(...codePoints);
}

function buildPopupHtml(props) {
    const areaHa = formatSurfaceAreaHa(props);
    const verificationChecks = parseListField(props['verification_checks']).filter(Boolean);
    const fields = [
        ['Area', areaHa],
        ['Stage', formatEnum(decodeEnum(props['stage'], STAGE_LABELS))],
        ['Intervention start', safe(props['intervention_start_date'])],
        ['Intervention type', formatEnum(decodeEnum(props['intervention_type'], INTERVENTION_TYPE_LABELS))],
        ['Pre-intervention use', formatEnum(decodeEnum(props['pre_intervention_land_use'], PRE_INTERVENTION_LAND_USE_LABELS))],
        ['Post-intervention cover', formatEnum(decodeEnum(props['post_intervention_land_cover'], POST_INTERVENTION_LAND_COVER_LABELS))],
    ].filter(([, value]) => value !== '');

    const visibility = (decodeEnum(props['site_visibility'], SITE_VISIBILITY_LABELS) || '').toUpperCase();
    const badges = [];
    // formatEnum() first, then check truthiness of the resulting label string — not
    // the raw props['site_type'] value, since code 0 (RESTORATION) is falsy in JS.
    const siteTypeLabel = formatEnum(decodeEnum(props['site_type'], SITE_TYPE_LABELS));
    if (siteTypeLabel) badges.push(`<span class="popup-badge">${escapeHtml(siteTypeLabel)}</span>`);
    if (visibility) badges.push(`<span class="popup-badge${visibility === 'PRIVATE' ? ' visibility-private' : ''}">${escapeHtml(formatEnum(visibility))}</span>`);

    const flag = countryCodeToFlagEmoji(props['country_code']);
    const checkPills = buildVerificationPillsHtml(verificationChecks);
    const photoIds = parseListField(props['photo_ids']).filter(Boolean);
    const photoUrl = photoIds.length && props['id'] ? buildPhotoUrl(props['id'], photoIds[0]) : '';

    return `
        <div class="popup-inner">
            ${photoUrl ? `<img class="popup-photo" src="${escapeHtml(photoUrl)}" alt="">` : ''}
            <div class="popup-content">
                <div class="popup-title-row">
                    <div class="popup-title">${escapeHtml(props['name'] || 'Untitled site')}</div>
                    ${flag ? `<span class="popup-flag" title="${escapeHtml(props['country_code'])}">${flag}</span>` : ''}
                </div>
                <div class="popup-badges">${badges.join('')}</div>
                ${fields.length ? `
                <hr class="popup-divider">
                <div class="popup-section-header">Metadata</div>
                <dl class="popup-fields">
                    ${fields.map(([label, value]) => `<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd>`).join('')}
                </dl>
                ` : ''}
                ${checkPills ? `
                <hr class="popup-divider">
                <div class="popup-section-header">Checks</div>
                <div class="popup-check-pills">${checkPills}</div>
                ` : ''}
            </div>
        </div>
    `;
}

function handleVisibilityToggle(event) {
    if (event.target.checked) {
        visibleStatuses.add(event.target.value);
    } else {
        visibleStatuses.delete(event.target.value);
    }
    mvt_tile_layer.changed();
    vector_tile_layer.changed();
    centroid_webgl_layer.updateStyleVariables({
        showPublic: visibleStatuses.has('PUBLIC') ? 1 : 0,
        showPrivate: visibleStatuses.has('PRIVATE') ? 1 : 0,
    });
}

const DEFAULT_LOGIN_ICON = `
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
        <circle cx="12" cy="7" r="4"></circle>
    </svg>
`;

function updateLoginButton() {
    const btn = document.getElementById('login-button');
    if (logged_in && current_user) {
        btn.innerHTML = current_user.photoURL ? `<img src="${current_user.photoURL}" alt="">` : DEFAULT_LOGIN_ICON;
    } else {
        btn.innerHTML = DEFAULT_LOGIN_ICON;
    }
}

function setLoggedIn(value) {
    logged_in = value;
    updateLayerVisibilityForRenderMode();
    updateLoginButton();
    document.getElementById('filter-panel').classList.toggle('visible', logged_in);
    if (logged_in) {
        // Clear previously-failed (unauthenticated) loads so they retry now that a token is available
        vector_tile_source.refresh();
        mvt_tile_source.refresh();
        loadAllCentroids();
    } else {
        vector_tile_source.clear();
        mvt_tile_source.refresh();
        centroid_source.clear();
        setCentroidsModeEnabled(false);
    }
}

function logout() {
    current_user = null;
    setLoggedIn(false);
}

async function login_clicked() {
    if (logged_in) {
        logout();
        return;
    }

    const result = await signInWithPopup(auth, provider);

    const whitelistRef = doc(collection(firestore, "site-verify"), "whitelisted_emails");
    const whitelistSnap = await getDoc(whitelistRef);
    const whitelisted = Object.keys(whitelistSnap.data() || {});

    if ((!whitelisted.includes(result.user.email)) && (!result.user.email?.endsWith('restor.eco'))) {
        alert("Access Denied: Your email is not whitelisted.");
        current_user = null;
        logout();
        return;
    }

    current_user = result.user;
    setLoggedIn(true);
}

// WebGLPointsLayer's hit detection (ol/renderer/webgl/PointsLayer.js) decodes the
// picked pixel's color into a feature-buffer index, then reads that index straight out
// of its render-instructions array as if it were always a valid encoded feature id.
// Real feature ids are encoded starting at 5 (`colorEncodeId(idx + 5, ...)`), but an
// empty/background pixel decodes to id 0 — index 0 of that array isn't a "no feature"
// sentinel, it's just the x-pixel-coordinate of whichever feature happens to be first
// in the buffer. That float gets floored and treated as a feature UID, so hovering over
// blank space can resolve to a real, unrelated feature (reported as: hovering off a
// Cameroon site anywhere else on the map kept showing a fixed, unrelated Australian
// site). This is an ol 9.1.0 bug, not something fixable from application code, so guard
// against it here: reject a centroid hit whose feature isn't actually near the pixel
// that was hit-tested.
const CENTROID_HIT_PIXEL_TOLERANCE = 6;
function isGenuineCentroidHit(feature, pixel) {
    const featurePixel = map.getPixelFromCoordinate(feature.getGeometry().getCoordinates());
    if (!featurePixel) return false;
    const dx = featurePixel[0] - pixel[0];
    const dy = featurePixel[1] - pixel[1];
    return Math.sqrt(dx * dx + dy * dy) <= CENTROID_HIT_PIXEL_TOLERANCE;
}

// Add the mouse move event
map.on(['pointermove'], function (mapEvent) {
    // Find the topmost feature under the mouse, restricted to the sites layers
    // (otherwise this also picks up basemap features, e.g. roads/boundaries, that
    // happen to carry an 'id' property, causing bogus "Untitled site" popups).
    // Uses forEachFeatureAtPixel (rather than getFeaturesAtPixel) so we know which
    // layer the hit came from, needed to drive the centroid layer's hover highlight.
    let hitFeature = null, hitLayer = null;
    map.forEachFeatureAtPixel(mapEvent.pixel, (feature, layer) => {
        hitFeature = feature;
        hitLayer = layer;
        return true; // stop at the topmost hit
    }, {
        hitTolerance: 5,
        layerFilter: (layer) => layer === vector_tile_layer || layer === mvt_tile_layer || layer === centroid_webgl_layer,
    });
    if (hitLayer === centroid_webgl_layer && hitFeature && !isGenuineCentroidHit(hitFeature, mapEvent.pixel)) {
        hitFeature = null;
        hitLayer = null;
    }
    // Popup position tracks the raw mouse position every event (so it follows the
    // cursor smoothly); its content/visibility is driven by the debounced, "confirmed"
    // hover target instead (see updateHoverCandidate/applyConfirmedHover above), so a
    // noisy raw hit-test doesn't flicker the popup or the marker highlight. While the
    // click context menu is open, the popup is fully pinned in place — position included —
    // until an action is taken, so it doesn't drift as the cursor moves toward the menu.
    if (!feature_menu_feature) {
        map_popup.setPosition(mapEvent.coordinate);
    }
    updateHoverCandidate(hitFeature, hitLayer);
});

// Show a small context menu (Zoom to site / Show site checks) when a site is clicked,
// for both polygon and centroid features. Uses forEachFeatureAtPixel (rather than
// getFeaturesAtPixel) so we know which layer was hit — mvt_tile_layer's features need
// different handling when zooming (see feature-menu-zoom below).
map.on('click', function (mapEvent) {
    let hitFeature = null, hitLayer = null;
    map.forEachFeatureAtPixel(mapEvent.pixel, (feature, layer) => {
        hitFeature = feature;
        hitLayer = layer;
        return true;
    }, {
        hitTolerance: 5,
        layerFilter: (layer) => layer === vector_tile_layer || layer === mvt_tile_layer || layer === centroid_webgl_layer,
    });
    if (hitLayer === centroid_webgl_layer && hitFeature && !isGenuineCentroidHit(hitFeature, mapEvent.pixel)) {
        hitFeature = null;
        hitLayer = null;
    }
    if (hitFeature && hitFeature.get('id') !== undefined) {
        showFeatureMenu(hitFeature, hitLayer, mapEvent.coordinate);
    } else {
        hideFeatureMenu();
    }
});

document.getElementById('feature-menu-zoom').addEventListener('click', function () {
    if (!feature_menu_feature) return;
    const geom = feature_menu_feature.getGeometry();
    const view = map.getView();
    if (geom.getType() === 'Point') {
        // Centroid features only carry a point, not the site's actual footprint —
        // zoom in on it at a reasonable fixed level rather than fitting a zero-area extent.
        view.animate({ center: geom.getCoordinates(), zoom: Math.max(view.getZoom(), 14), duration: 400 });
    } else {
        // mvt_tile_layer's VectorTileSource defaults to EPSG:3857 (Web Mercator) —
        // unlike vector_tile_layer's FGB-sourced ol/Feature objects (read with
        // featureProjection explicitly set to the view's EPSG:4326), its
        // ol/render/Feature geometries are left in that tile-native EPSG:3857 space.
        // OL's tile renderer reprojects on the fly at draw time, but raw .getExtent()
        // access here doesn't, so feeding it straight to view.fit() (which expects
        // view-projection EPSG:4326 coordinates) produced NaN. Reproject first.
        let extent = geom.getExtent();
        if (feature_menu_layer === mvt_tile_layer) {
            extent = transformExtent(extent, 'EPSG:3857', 'EPSG:4326');
        }
        view.fit(extent, { padding: [80, 80, 80, 80], duration: 400, maxZoom: 16 });
    }
    hideFeatureMenu();
});

document.getElementById('feature-menu-checks').addEventListener('click', function () {
    if (!feature_menu_feature) return;
    openChecksModal(feature_menu_feature.getProperties());
    hideFeatureMenu();
});

document.getElementById('feature-menu-restor').addEventListener('click', function () {
    if (!feature_menu_feature) return;
    const siteId = feature_menu_feature.get('id');
    if (siteId === undefined) return;
    window.open(`https://restor.eco/sites/${siteId}`, '_blank', 'noopener');
    hideFeatureMenu();
});

document.getElementById('checks-modal-close').addEventListener('click', closeChecksModal);
document.getElementById('checks-modal-backdrop').addEventListener('click', function (event) {
    if (event.target === this) closeChecksModal();
});
// Escape closes one layer at a time — the topmost/most specific thing currently
// open — rather than closing everything at once regardless of what's showing.
document.addEventListener('keydown', function (event) {
    if (event.key !== 'Escape') return;
    if (document.getElementById('checks-modal-backdrop').classList.contains('open')) {
        closeChecksModal();
        return;
    }
    if (feature_menu_feature) {
        hideFeatureMenu();
        document.getElementById('popup').style.display = "none";
        return;
    }
    document.getElementById('popup').style.display = "none";
});

// Displays the slider's underlying km² threshold in whichever unit reads more
// naturally at that size — ha below 1 km² (where the exponential slider spends most of
// its range), km² at or above it — rather than always km², which would round tiny
// thresholds like "1 ha" down to "0 km²".
function updateSliderLabel(areaKm2) {
    const valueEl = document.getElementById('slider-value');
    const unitEl = document.getElementById('slider-unit');
    if (areaKm2 < 1) {
        valueEl.innerText = formatNumber(areaKm2 * 100);
        unitEl.innerText = 'ha';
    } else {
        valueEl.innerText = formatNumber(areaKm2);
        unitEl.innerText = 'km²';
    }
}

// Update layer style when slider changes
document.getElementById('slider').addEventListener('input', function () {
    const areaKm2 = sliderPositionToAreaKm2(parseFloat(this.value));
    updateSliderLabel(areaKm2);
    mvt_tile_layer.changed();
    vector_tile_layer.changed();
    centroid_webgl_layer.updateStyleVariables({ thresholdHa: areaKm2 * 100 });
});

document.getElementById('mangrove-proximity-toggle').addEventListener('change', function () {
    mangroveProximityOnly = this.checked;
    mvt_tile_layer.changed();
    vector_tile_layer.changed();
});

// Ensure the script runs after the DOM is fully loaded
document.addEventListener("DOMContentLoaded", function () {
    let visibilityCheckboxes = document.querySelectorAll("input[name='options']");
    visibilityCheckboxes.forEach(checkbox => {
        checkbox.addEventListener("change", handleVisibilityToggle);
    });
    document.querySelectorAll("input[name='render-mode']").forEach(radio => {
        radio.addEventListener("change", handleRenderModeChange);
    });
    document.getElementById('login-button').addEventListener('click', login_clicked);
    updateSliderLabel(getAreaThresholdKm2());
    updateMangroveFilterAvailability();
});